


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useSSL=false&serverTimezone=UTC
    username: user
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialet: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      hibernate:
        type: trace
