
server.port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/academia?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace
